name: Continuous Integration
env:
  DOCKER_BUILDKIT: 1
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  dockerfile:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: OCI Image Supported Platforms
        id: platforms
        uses: ./
        with:
          dockerfile: tests/Dockerfile
      - name: Assert Dockerfile Platforms
        uses: nick-fields/assert-action@v2
        with:
          expected: '["linux/amd64","linux/arm64"]'
          actual: ${{ steps.platforms.outputs.platform }}
          comparison: exact
  supplied-image:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: OCI Image Supported Platforms
        id: platforms
        uses: ./
        with:
          dockerfile: tests/Dockerfile
          image: ghcr.io/wyrihaximusnet/php:8.3-zts-alpine-dev
      - name: Assert Dockerfile Platforms
        uses: nick-fields/assert-action@v2
        with:
          expected: '["linux/amd64","linux/arm64"]'
          actual: ${{ steps.platforms.outputs.platform }}
          comparison: exact
